### ISSUE TITLE
Issue with color customization of macro buttons

### ISSUE THREAD

**Issue by WatchingWatches** [OrloDavid/Kustom-Kobra-Klipper#1]
Thank you for sharing this awesome theme with us. I found a small issue, where the color of the macro button ca not be changed. This is how it looks like:
![image](https://github.com/OrloDavid/Kustom-Kobra-Klipper/assets/106354710/3a207b36-6b8f-4e84-a121-306bc6c56bbf)
And this is how it should look like:
![image](https://github.com/OrloDavid/Kustom-Kobra-Klipper/assets/106354710/328d4211-2316-4ddf-8d36-7bef3059315c)
This is not a big issue, but it would be great if it works.
For the installation of the theme i recommend using the git clone method. I trayed only cloning the .theme folder, but on my pi it didn't work for some reson. On the Pc it worked with the same commands.

**Comment by OrloDavid** [comment]
Yes, the theme overwrites them. Let me see if I can find the specific CSS to break out the macro buttons from the rest. I will then comment the Macro buttons to make them easier to turn on or off. 

Does that work? 

> Thank you for sharing this awesome theme with us. I found a small issue, where the color of the macro button ca not be changed. This is how it looks like: ![image](https://private-user-images.githubusercontent.com/106354710/311437670-3a207b36-6b8f-4e84-a121-306bc6c56bbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDA4MDAsIm5iZiI6MTcxMDMwMDUwMCwicGF0aCI6Ii8xMDYzNTQ3MTAvMzExNDM3NjcwLTNhMjA3YjM2LTZiOGYtNGU4NC1hMTIxLTMwNmJjNmM1NmJiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMzI4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODgyMGFmNjFmMjQ0NTdkYzcxNDczYzdkNzMwZDllOGUwOTk3MmRlNzk4YThiYWMzYjAwYTkwMDI1M2U4M2Q4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TiOdqLUExOKckcXp5C2vHyOysni0o33DG3S-R0RTTrA) And this is how it should look like: ![image](https://private-user-images.githubusercontent.com/106354710/311437840-328d4211-2316-4ddf-8d36-7bef3059315c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMDA4MDAsIm5iZiI6MTcxMDMwMDUwMCwicGF0aCI6Ii8xMDYzNTQ3MTAvMzExNDM3ODQwLTMyOGQ0MjExLTIzMTYtNGRkZi04ZDM2LTdiZWYzMDU5MzE1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMzI4MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzVkYTgwZWVlYWU5YjY5NjkwMDhkZWEyNGQwMjk5ODBhMzIyN2Y4NGY3ZTliYjIyMzU2MTNkNzhiN2RlNGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.log36_dgOkZ1Md0enw43gIvFF-PNYUM8oYuTSOY6vko) This is not a big issue, but it would be great if it works. For the installation of the theme i recommend using the git clone method. I trayed only cloning the .theme folder, but on my pi it didn't work for some reson. On the Pc it worked with the same commands.

**Comment by OrloDavid** [comment]
Download latest CSS and change

`.theme--dark.v-btn.v-btn--has-bg{
     color: var(--White) !important; /* Text on Buttons - Enabled - All Including Macro Buttons*/
    background-color: var(--Black) !important;  /* Buttons - Enabled - All Including Macro Buttons*/
}`

To 

`.theme--dark.v-btn.v-btn--has-bg{
    /* color: var(--White) !important; /* Text on Buttons - Enabled - All Including Macro Buttons*/
    /* background-color: var(--Black) !important;  /* Buttons - Enabled - All Including Macro Buttons*/
}`

**Comment by WatchingWatches** [comment]
Thank you for the fast and easy fix! It worked. It's also great, that you took all of your own config files outside of this repo.

**Comment by OrloDavid** [comment]
I still have a ton of stuff to upload, I wasn't planning on a dedicated repo for everything I've made over the last 5 months but I don't really see a better way, 

I'd hate for some of it to be overlooked if someone needs / wants it, like the uVision scripts I made, I have rheumatoid arthritis and just from doing those damn groups and C++ Dirs. when creating a new project, my right hand puffed up and was down for a day. Those scripts save u from all that bullshit.

Or the Centered-Z mod I've done, I really need to dedicate more time to promoting that, its honestly the best Z solution for Cart based printers. I'll never go back after that mod. Anyone with a single Z setup should be doing this mod, at least Rev.1 which requires some printed parts, nuts and bolts. I wanted to finish Rev.3 but I suppose I should just get the damn Wiki's done already. 

BTW- Did you see I made a universal Klipper Themed version of this? It's in my Repos

**Comment by WatchingWatches** [comment]
Yes i have seen the vibrant 80s mainsail theme too. Also a cool theme. With the changes to the css now the standart text color of the macro is pink which looks great. 

I watched a Youtube video of the centered Z mod. Nice and simple fix. I personally have a ender 5 pro, which has the z axis moving the printbed around, so i don't have this problem. 

 Currently i enjoy writing postprocessing scripts in python, which can modify gcode after slicing. My next project is adapting the CNC-Kitchen Cura plugin, which can modify the infill to work in prusa slicer. 

I hope your hands are getting well.

**Comment by OrloDavid** [comment]
Thank You, the hand swells mostly while working in Mesh Mixer on models, I am now ambidextrous with a PC mouse :) The left hand is catching up though, as this type of arthritis generally effects both sides of the body equally. Currently my left wrist is more in pain, but I can feel the same issues in both. This and a host of other stuff was dormant but awoken after getting COVID. I was unaware that things like this, Graves, Type-1 diabetes, were commonly diagnosed in adults who had another disease trigger them. Thyroid, Arthritis, Heart & Neurological issues are very common on my mother's side of the family.  I've come to terms with all of it, now I just want to get as much done as I possibly can as these issues and others are progressing at breakneck speed. My smartwatch keeps telling me I need more sleep, I tell it, there will be plenty of time for that later.

I really should update those videos. I have so many little projects going on, it's just hard to stay focused on one as some parts of the process take time, receiving parts, waiting for uploads or other processing, whatever it may be. So, I jump from project to project to keep the momentum going on each. 
If I could pay someone to full time document for me, I would. Sad thing is, I know very well from my profession, if it's not documented properly, it never happened. 
Without good docs, the best thing in the world is trash. 
The iPhone may have not needed them for the end user, but what about the Devs that made all those cool apps. 

Yep, my mod does not apply to Core-X-Y, hey that rhymes. 

I did glance at your Git, I'll admit, my Python sucks. I started in Auto IT, made some really cool shit, have a repo for that.
I then learned Arduno / Wiring and later C++, which kind of just made sense after wiring,
That transitioned me into PowerShell which I still use and prefer over Python due to my day job.

 I am a Consultant / Net Architect / Net Engineer, and to give a recent example: 
 I needed to automate gathering switch info from live Cisco switches @ Corewell Health Medical Mile buildings during the Spectrum Health + Beaumont merger which I was Lead Network Engineer on. There is NO WAY I was getting Python to run on their network without lots of alarms and hoops to jump through. I had very high-level access, but we are talking enterprise networking, multi-location, big data center, entire levels of support teams. Getting things done, changes, approved, requires multi-step processes which I just didn't have time for. The entire team did not have time for that. We were in a crunch; PowerShell was the only viable solution and as such I was happy to be fluent in it. 
This info was then aggregated into a CSV which was converted into Excel books combined with data from their inventory management systems, i.e. IPAM, ISE, Prime, Etc. It was a fun project, lots of days with 2hrs sleep. 

I did want that Gradient Infill on my most recent print. I ended up using the adaptive cubic in Orca slicer, but what I really wanted was Gradient Rectilinear.  Because Rectilinear is pretty much all I use, mostly due to CNC kitchens videos, and the fact the lines actually get thinner is a pretty neat trick. 
Pressure Advance tells me that the base functionality is there on modern hardware, and of course it's working in Cura, now I suppose it's just doing what you're doing, and porting it to different platforms, I admire that and am excited to see the end result. 
I'm curious how long it would take to get from Prusa Slicer to Orce. I'd be happy to be a test guinea pig, I can bumble my way through some Python when necessary.

**Comment by WatchingWatches** [comment]
At my university (i study mechanical engineering) i only learned the basics of programming in python and matlab. The general best thing you learn is breaking complex problems down in smaller and easyier problems you can solve. This semsester i had a course, where we got a rasberry pi, acceleration and temperature sensors to do experiments and analyse the data. I learned about data management, but not that much about actual programming. I had more joy programming my postprocessing scripts, which require a better understanding of loops and espacially nesting of those.

Last year i was part of a formula student team, which builds every year an electric and autonomous drivig racing car. At the end of the season we compete against other teams. I was part of the accumulator departemend and part of my job was the cell testing. I programmed a "script" in LabView, which is a graphical programming language (you basically connect functios with wires, often used to control big systems), to control a powersupply and simultaneously measure the voltage and temperature of the battery cells. This was importent to ensure, that the perfomance of each cell is the same and that they would meet our requirements.

Orca slicer and Prusa slicer are very simular, since Orca slicer is based on Prusa and Bambu slicer. Postprocessing scripts are initiated the same way in both. The script gets called after saving the gcode. This means, that you can't see the result of the script in the preview after slicing. Also there is not an easy way to insert the varibles of the script inside of the slicer. I will probably read those with an input dialog in the terminal. I haven't actually started with programming this script yet. The script will rely on the verbose gcode setting, which adds a comment after each G1-3 line with the feature type. This way the program can modify only the infill. In prusa and orca slicer these comments are the same, so there is a good chance, that they will work regardeless of which one you use. Thanks for the offer to be my tester. I will let you know when i have a working version. I can't tell how difficult and long it will take.

**Comment by WatchingWatches** [comment]
Hi i just wanted to let you know, that i uploaded the gradientinfill script for prusa slicer this moment. You can find it [here](https://github.com/WatchingWatches/GradientInfill/tree/master/Prusa). I also wrote a script for orca slicer, but had some difficulties. If you are interested i can also push this script, which currently doesn't work when called from slicer. It's crazy that no one else adapted the script before to another slicer. I had to make a few changes, but the main algorythm is the same.

**Comment by WatchingWatches** [comment]
Hi I just wanted to let you know that I have a well working version of the gradient infill script for Orca slicer [here](https://github.com/WatchingWatches/GradientInfill). I just made a pull request at the original repository of CNC kitchen (my first ever). I don't know if anyone else has tried my scripts so far (even though a few people were interested) so it would be great to hear if it's working fine for you as well and if the Readme has clear instructions.

**Comment by OrloDavid** [comment]
Trying this out now, sorry for the late reply. I had a reply typed up but then needed to reboot my laptop and lost the reply. 

Your screen name popped in my head while I was designing some watch faces for my watch, I was thinking "I wonder what kind of watches does watching watches watch" haha 

I'm printing this skull I designed, I've printed it and a few variations on it already. I noticed when I use Glow PLA I can see the infill pattern and I would like it thicker around the walls, which would also help with the glow. I think this is the perfect script for that. 
The glow PLA seems to be very picky when printing, need to go really slow and under extrusion can become an issue, especially during infill. So, this will really put this script to the test, I'm going to run it slow, I'm guessing it will take about 2 days to print.

**Comment by WatchingWatches** [comment]
What a coincidence. I'm into mechanical watches and at the time i came up with the name i watched many Youtube videos about watches, so this is where the name comes from. I actually bought my 3d printer because i wanted to print models of mechanical watches to understand the working principal better.

Are you designing watch faces for analog or smart watches?

Your project sounds like an great idea. I haven't thought about this application.
 If you want to have thin lines in the core i recommend to do this (from the READMe advice section:
When you look at the second picture you can see that the flow in the inner core (outside of the GRADIENT_THICKNESS range) isn't changed. If you want a thin infill width in the core (where the forces are the lowest) you can choose a small linewidth as infill linewidth, set MIN_FLOW = 100 and adjust MAX_FLOW accordingly (increase).

I recommend to print a small test print before starting such a big print, because if the maximum flow is set too high the quality of the perimiter will be worse.

Maybe in the future i will implement a maximum flow rate for the infill so you don't have to change the overall infill speed in the slicer. Especially with large infill this can increase the print time by a lot.

I'm curious how your print will look like. If you have any problems with the script just contact me. In the README should be all important details.

**Comment by OrloDavid** [comment]
I've been experimenting with various smartwatch faces using Facer, similar to Tinkercad, allowing for complex designs with coding or built-in functions.  I tried my hand at a more direct development process for watches when I explored LVGL with Squareline Studio. At rhat time I planned to integrate a 1.28" touchscreen with built-in accelerometer into my printer, this was before the Nomi, but eventually found it a royal pain to program for and set it aside.
https://www.waveshare.com/1.28inch-touch-lcd.htm

My attempts to operate anything from Squareline on this device were unsuccessful across multiple platforms including Arduino, VS Code, Eclipse, and Visual Studio 2022. My frustration with the GNU Arm Toolchain grew as I ventured deeper into programming for development boards that require detailed toolchains and hardware-level coding.

Then Facer released its studio web app, which you have to pay for, and that doesn't cover the mobile app standard membership fee (which isn't needed to just design and use your own). I've managed to create a few watch faces, mainly to familiarize myself with the web app's functionality. This approach helps me anticipate potential issues and enhances my efficiency, as it feels like I've mentally rehearsed the process beforehand.
https://www.facer.io/u/davidorlo

I was curious about the watches, and assumed they were likely analog, because I was wondering if any would be cool to do a digital tribute style face but maybe more modernized. 

I'm a bit of a watch guy, but my collection isn't anything special. My favorites are a few limited run watches from TokyoFlash that I purchased back in 2010, or somewhere around then. 
https://tokyoflash.com/

I own these two
Original Rogue (this was a very limited run compared to the Rogue Touch)
https://tokyoflash.com/collections/watch-museum/products/rogue-sr2-lcd-watch

Uzumaki
https://tokyoflash.com/collections/watch-museum/products/uzumaki-analog-watch

I did a tribute to this watch, the profile preview of the watch doesn't show correctly but this link does
https://www.facer.io/watchface/G32uzNXfja?watchModel=ticwatchexpress



I'm uploading the 3D models to Thingiverse, and some pics of previous prints. I will post a link once they are done.

**Comment by OrloDavid** [comment]
Here are the models I made, I am printing the one with horns.

https://www.thingiverse.com/thing:6597318

https://www.thingiverse.com/thing:6596664

**Comment by WatchingWatches** [comment]
Cool and interesting watches. I didn't know this brand before. 

I see you have a favorite color combination.

Your project reminds me of one of my own projects, which is about a physical dashboard for sim racing.
I used an arduino to read serial data from a python script, which gets the data from the game. The arduino then controls a servo representing the RPM, leds and an digital number segment for the velocity. I somehow forgot about the project and never finished it.

My favorite watch company is Sinn Spezialuhren which is from Frankfurt close to where i live. They use simple, but good mechanical movements and think about watches as tools. They built them not like watchmakers, more like engineers. They make some watches from U-boot steel and have a special surface hardening technic which increases the hardeness of stainless steel from 300 Vickers to 1200 Vickers, which means that even decade old watches don't have any scartches on the case.

I have this simple watch from them: https://www.sinn.de/de/Modell/556_A.htm
I bought it used a couple of years ago.

The skull looks great did you model it with blender?

I wanted to learn blender, but it was very different from the parametric CAD programs i'm used to.

**Comment by OrloDavid** [comment]
I can barely get anything done in blender. As soon as I feel I'm ready to try it again, I come to the same conclusion which is, unless I plan to work in blender as a full time hobby, it's not worth the time investment. Especially for someone like me, who knows plenty of other tools to get similar effects or desired result. 

When I wanted to make a 3D logo for my business I tried it again, then gave up after a day with little progress and was able to make something that looked 3D in Photoshop within an hour. 


The skulls were started in 3D builder but Tinkercad would have been my primary choice, if I wasn't forcing myself to learn 3D builder so I can maybe quit Tinkercad all together. I'm sick of the uploads that never complete or models that never fully load or load with errors. Not to mention if I want a hybrid model, like the part coolers I made, then I need to switch between the two which means compressing the models down further than necessary if I wasn't working in a cloud only app.


The second and more important part of the modeling was in meshmixer, it's a really powerful app when you start to learn everything it can do. It's a shame because 95% of the videos on YouTube are all dumb shit, like how to mix your square model with your elephant, or some other dumb shit.

I get it, the name is mesh mixer, but that doesn't mean that's all it can do, is actually not even what it's good at or best known for by those who really know how to use it.

If you can sculpt clay like a novice and paint a little in real life you will likely instantly get it. The concepts and way the material moves are very similar and easy to draw comparisons. One thing I suggest though, in the beginning turn on the wire frame, it will help you see what the tools are actually doing, then it's easy to predict or know what tool to use. Another pro type, is if your going to sculpt an existing model that you downloaded, use the "make solid" function first, there are several reasons for this which will become apparent over time. You could also Remesh, but that takes longer and it's something I usually save until the end. 

Make solid, leave drop down on fast or whatever, only use accurate if you really need it, the other sharp edge option sucks. Then drag the first slider all the way to the right, the second one around 325, higher if you need now detail. If your PC struggles to much at those settings then do a mesh reduce, don't Remesh or make solid again. Making solid layed down your new foundational geometry, reduce is simply reducing it to make things easier on your machine. When I'm completely done, I often Remesh with defaults then reduce by as much as 85%, usually 65%, because the extra triangles can't even be used for most printers. 


I like the watch, with the black strap it really sets that face off. 
Elegantes U-boot, das die Zeit an Ihrem Handgelenk anzeigt. 

I think I might make a digital version inspired by your watch and the U-boat gauges. Would be interesting to mix elegant tool-first engineering design and rugged function-first mechanical design. 

My skull print is nearly done, I didn't end up altering the settings because I was in a hurry when I started it. It doesn't look like it made much difference internally. I'm unable to tell that the lines are varying in width. 
I can try again with the same model. I had a tree support that tipped over and may have caused some damage to one of horns. 
I also promised a few people these skulls and that are the biggest print I have that I think this would be good for.  The only other model I need to print a bunch of, are those articulated lizard looking toys I designed. I donate them for kids when I can. 

Such is life.....

**Comment by OrloDavid** [comment]
Oh, and the gauge project sounds cool. One of the first animated software designs I did was analog style gauges for PC monitoring. 

Speaking of separate displays got me thinking how much harder that type of stuff was back then, but then I thought about LVGL and realized, maybe it's still the same haha.

But that got me thinking about something else, did you see the GitHub project for a dedicated KlipperScreen, designed to run on-host? And it uses the LVGL library, probably Square line studio and the built in 3D printer demo, haha, that's what I would have done. Why reinvent the wheel, just skin/theme the hell out of it. 


I can find you a link if you can't find it. I haven't tried it yet but plan to. I tried KlipperScreen and I didn't like it. I use the full webpage on my little 7" low res touch screen, with he browser set to 67% zoom.

**Comment by WatchingWatches** [comment]
Hi this time i forgot to answer. Sorry. 

Do you have a direct drive extruder on your printer? The Cura version of the script (inside of the slicer made by someone else than cnc kitchen) has a feature to change the feedrate. He wrote that bowden extruders have trouble without, since you actually have a pressure gradient inside of the nozzle on the infill. I think i can implement this and add the option of a maximum flow rate in the future. Did you take a look at the maximum flowrate in a previewer?

Thanks for recommending meshmixer. I will give it a try. Currently i am experimenting with the Fusion360 python api. With help of some math i learned i made an hourglass made from many spheres. Originally i wanted to use OpenSCAD, but rendering models like this takes a lot of time and in fusion it takes less than a minute. It's also possible to edit the model the "normal way" in   fusion which is a big plus for me.

I haven't seen the GitHub project for a dedicated KlipperScreen yet. It would be great if you could share the link. Do you mean by run on host running on the lcd display of the printer? If yes that would be very inetersting to me, since i don't like the interface that much. I only use it sometime to heat the nozzle for filament changes.
To acess my printer i use my laptop with Mainsail. To take a look during a print i use the Octoapp, which also notifys me when the first layer finished or the print finished. The Mainsail interface is quite good, so if i need to make a quick change i use that.

**Comment by WatchingWatches** [comment]
Hey i wanted to notify you that there was a bug in the Gradienfill script in combination with supports, which is now fixed. I just implemented the maximum flow feature, which will be public in the next few days.

**Comment by OrloDavid** [comment]
Sorry for the delayed response, I've been learning everything I can of AI Models and image manipulation., It's been a lot to take in but I've gotten pretty damn good at upscaling shit video, such as highly compressed 426x240 @ 24 fps video, mostly just with people though. And if your mind went straight to old porn home-video, I'd say shame on you, and your partially correct. It's something like that, but for an altruistic motive. I'm finally nearing an end to the work which I hope to have wrapped up by end of this week, 

I do have direct drive, Biqu H2 V2S, love that thing.
I did have lots of support in my model. I still haven't finished putting my printer the rest of the way together, It's just been sitting idle, waiting for something to do. This other project took all my attention because I'm on a deadline to have it done. 

I'll find you the link for Klipper Screen, someone else has a project to try to use default printer screens but honestly, I don't see the point, a decent 7" touchscreen is cheap on Amazon and even cheaper on Aliexpress. 

The project I was referring to runs native, meaning that its an actual App on the computer running klipper instead of this weird web api thing that's designed for remote screens, even though can run it local. If you had a decent screen for the printer then this would still be a plus and the way to go. If you could run the current Klipperscreen on the stock LCD screen then it would make sense, but running that cut down GUI on a decent LCD, even if its only 5", just feels like your cheating yourself.

**Comment by OrloDavid** [comment]
Here are the links

https://github.com/ballaswag/guppyscreen

I think i saw a few repos for using the stock LCD, these are instructions are for an Endr but can be duplicated for just about any LCD with a little EE knowledge. Some printers will do funky things with the IO which could make the job tougher but if you used a PICO to control the LCD instead of your stock board, or an aftermarket board like an SKR, then it should work with any LCD as long as you can find some driver library for it.  But again, if you have to buy a Pico or other stuff, just buy a HDMI LCD touchscreen instead and plug it into your PC or rPi and be done with it.

https://github.com/RobRobM/DWIN_T5UIC1_LCD_E3S1

**Comment by WatchingWatches** [comment]
Impressive work these kind of things feel like magic to me. Is the Ai actually able to improve the picture quality, while maintaining a true representation of the moment or is the Ai filling in pixels with color which make sense, but might not be what the picture did look like? 

I just pushed the GradientInfill script with the added volumetric flow limit to a new branch [here](https://github.com/WatchingWatches/GradientInfill/blob/limit_volumetricflow/Orca/orca_addGradientinfill.py). I will merge it once i tested it intensly. You said you couldn't tell a difference in line width at the print. Did you check in a gcode previewer if the script worked correctly? If the script would have done no modifications it would have told you so though. I've also heard from someone, who wants to use this script for TPU and control the stiffness of the print with the script (commercial application). The cool thing is that you don't have to take use the walls of the print as refernce points. You can choose custom coordinates for these kind of application. I've also added a special script which uses the outer perimeter as a refence point, but then deletes the perimeter gcode, so you end up with the infill only ( there is a small bug in there though). I think like this i can show off the script the best, so people are able to see the different line width in 3 dimensions, rather than 2.  

Thanks for sharing the links i will take a look.

**Comment by OrloDavid** [comment]
The question on how the AI upscales is completely dependent on the AI model used. Think of most AI as mini applications for a specific task, but instead of someone programming the complete code, they use training sets and train the application to perform very specific functions. 
ChatGPT and others like it, are a very specific type of AI called Large Language Model or LLM for short. They are trained with huge datasets, and tested on those datasets, then based on the correct answers the AI will be rewarded for example, the AI will get better at whatever dataset is chosen, i.e. coding, language interpretation, cooking, stamp collecting, etc... 

Everything is much more simplistic than it seems, especially when someone breaks it down into plain language. 

The whole AI thing is much more confusing and convoluted than it needs to be. As projects merge and hopefully the terminology starts to branch off, at least for the term AI, which is like describing everything you hear as sound, i.e. music is sound, genres of music are now just sound, an alarm is sound, ambient noise is sound, and so on. Everyone just calls everything sound, imagine that and you have an idea of what it means when someone says "AI".

It's like when everyone was saying "cloud" and not understanding it literally meant ANYTHING, it didn't even have to be on the internet, hence "private cloud". These buzz words make my life hell in IT, not because I need to address any of it, but because it's like nails on a chalkboard anytime I hear someone say something like "no, don't backup your data online, you should back it up in the cloud", or something that equally doesn't make any sense. And here I am, mentally scolding myself for visualizing the Blind leading the blind around which ever office I'm working from. 

For the most parts it's a lot of trial and error. I find myself running a set of random frames though sets of models and then comparing and choosing for the next step in the process quite often. Some steps I offloaded onto my photo program and then in-between I would use AI for various tasks. The one that I think it's great at is interpolation of frames. This is usually a fairly quick process depending on the obvious factors, video size, length and PC hardware. If you're interested, I recommend Flowframes on Github, it's easy to setup and use. If you're interested let me know and I will give you a quick little guide to get it setup for your system. Another great one is Enhancr on Github but it's a bit finicky to get it setup. Once Enhancr is configured, it has a tab for upscaling and one for Enhancing the video, the Enhancing tab is useful for most people and does an OK job.

Neither of those apps when using interpolation affect the overall video quality, or they shouldn't really. They create new frames in-between frames to give a smooth playback and the overall impression of improved quality. 

In my situation it was absolutely paramount that every single detail be preserved. I wanted to smooth areas that had blocking, remove noise, darken and highlight features, but not alter any usable detailed content. I will just tell you what this was for, I don't think I need to worry about you sharing the secrets of this with anything and I will publish some details to it once it is all complete. I am working on a new upscaling guide right now as a matter of fact. Its very detailed....  Covering AI's, Models, Apps, how to set everything up, what everything means, the upscaling process, and so on.

So, this one will be filed under my "I did a thing" projects and will start something like this. I downloaded an open coding and language model with no restrictions, specifically dolphin-2.7-mixtral-8x7b-GGUF by The Bloke. I originally set out for something different but then changed gears. I started learning everything I could find on Image/face recognition that would fit the task. Then video manipulation, frame extraction, and finally unique fingerprint ID's for images. I built this in Azure but it was too slow and pricey so I moved it to private servers and a few shared servers hosted at 1and1.com . I essentially built a 1 shot face recognition system which uses several popular face recognition techniques. The one I am most proud of is a hybrid technique in which I borrowed various pieces from research papers to create something similar to how your phone detects your face, but instead uses a short video clip and AI to determine depth based on objects in the scene. These are all captured into a 3d model and stored as a face to recognize. Associated with that is a folder of as many headshots as you can find of the subject, those are used later for reverse verification. 
I had a hunch to search for my ex, I have two children with her and I know of, and she told me of molestation by her father, a man that is still around my kids because she has physical custody and we live in different states. Her parents live near her, and I feel the clock is ticking before something happens to my daughter. There has already been very questionable behavior. I know the courts wouldn't side with me on my word alone. It was a long shot but I began using my new uncensored coding AI to assist me with coding a coding a platform that would intelligently catalog all of the porn, yes, all of it, or die trying. 
If your unfamiliar with any of my work, see the FFXI stuff I did 20 years, that was pretty much like programming AI, way back then. My code doesn't use hooks, so it literally plays the game like a human. I programmed all that by myself, Its something I'm fairly good and enjoy doing. 

The programs essentially search porn sites, starting with the biggest then I set it to searching google for specific terms and finding new porn sites, sometimes coming from redirects from other sites and cataloging where it's been. My ex is Indian and American mixed (Not American Indian, but India Indian), So I started it with terms that would fit around that, her father is Caucasian so that was added into possible search terms.  Once a potential hit is found, the frames of the video are separated and deduplicated. Then frame by frame they are reverse compared against my user database to check for hits, then log those hits on a scale of 0-1, i.e. .59, .98, etc.. And which frame-to-picture match was found. All of this work would make checking the false positives easier. 

I found a .99 positive match that matches 93% of face recognizable frames with scores averaging .65+, and topping out at .99 match between 3 frames and 1 photo. 

Thats the video I have been working on, not just cleaning it up but proving who the video shows. The most anxiety inducing of the workload was getting pictures of my ex. I really didn't have any after we split. We removed each other from online photo sharing, and I had gone through some phones while cleaning old photos along the way. But I had hope, I had an old 3TB Seagate hard drive, but the drive was an external and I had plugged in the wrong power supply, so it was dead. I found a replacement board, which needed to match MUCH more than I originally thought, The Serial #, Part #, Firmware Version, Origin of Manufacture, and on. I couldn't believe how many different 3TB Seagate drives were made. After installing the board, the drive would spin up and that's all, nothing else, but it was progress. Some research taught me that I would need to move a small 6 pin chip from the old board to the new. I did this and could now see the drive, but the partitions weren't mounting. I later found out that this was due to something with the external encloser and the 2TB limit in Windows. The short is that windows see the drive as 4096kb blocks but the case is translating that to 512kb and so they two don't match, or something along those lines anyway. 

I was able to load Linux Mint on my laptop using a fast external M.2 drive, then I used data recovery command line tools to recover all the photos on the drive. During this process I lost my Windows install on my internal M.2 drive, which I still have no clue why Mint decided to repartition it when it wasn't part of the selected install process. But historically Linux installers have been total shit, and it appears they have gone beyond shit and are now wreck less endangerments to one's mental wellbeing. I can't fully blame Mint, Ubuntu was named all over the fuckup, so I know who wrote the code, but shame on Mint for not knowing better to doublecheck anything released by the Al 'Mighty 'we will tell you what's good for you' Linux Distro.  I digress.

This should answer any and all things I was coy about, such as why I needed to preserve details throughout this process but fix things such as white balance and make a copy that could be played on a 1080P screen, such as in a court room.  The rest of my time has been consumed with writing a dissertation of a court filing, that explains how I am just handing over an open and shut case for them. Basically, walking through the video, where it came from, my process for upscaling so it can be repeated to verify no manipulation, all the photos that hit and things I know of them to verify the video, and even my own basic investigation for myself to be sure, prior to continuing. Things like researching the video itself, 240p at 24fps, this narrows down the likely device and years in which the video was made. I list the possibilities and even give step by step instructions on how to procure the information from the Porn site which can be used to find the IP and ISP, which then can be used to find the exact location the video was uploaded from, or who held that public IP at the time. I figured I might as well toss in the last bit since it was coming from a certified expert in the field. 

I have about a day or two left on everything and then it's in the hands of the police and courts. This is a onetime only thing, if there is anything else out there or anything at all, it will be scrubbed after this. So, I knew I had to spend the time and get this right. I also know that seeing my kids will be hell after this if I don't win custody proceeding this case. I'm taking a big swing, but I'd do the same for any children, doesn't have to be mine. 

I don't know how much my ex checks in on things I post online, but its why I have been so silent lately about things. I don't want to tip anyone off. 

So, that was a very long explanation to your question. For the work you have done, I am excited to try it. I still need to finish reinstalling everything on my Klipper Host so I can start printing again. I really should get that done soon but I have been so focused on this, as I said, I feel like I am in a race against time and every single day counts so much that it makes it very hard to focus on anything else. Its been like this since I was notified of the hit, which was in March, the system went live in February. I have since shut it down as the hosting is becoming too expensive to justify without a purpose any longer. I had thought about creating a website that allows users to essentially do the same thing I did as a free service with limitations, and paid service with extended features such as the amount of sites searched, the length of time the search will run and so on.  The biggest thing is, in order to convert it to a public service, I would need a ton more storage, so I have shelved it for the moment.

**Comment by WatchingWatches** [comment]
Thanks for the detailed explanation. Sounds like you have been trough a lot lately. 

I hope you got the custody for your children and you and them are safe.

This project could potentially be an important tool against abuse and for justice. In media Ai is often seen as a dangerous tool. This is a perfect example to show how it can be used for good.

I currently have a lecture about mathematical principals for machine learning. The lecture is mostly about different solving mathematical balancing problems, where you try to find a function, which describes the data with the help of iterative and non iterative methods. The exam will be in written form so programming isn't the focus, although this is how you do it in reality. There is an exercise in Matlab though, where we get some data and need to solve a problem.  In mechanical engineering programming isn't taken that serious at my university (at least in bachelor), so many people don't do the programming exercise. For the people who know a bit about programming this is a good way of learning, because doing these kind of calculations by hand can be quite boring especially iterative methods. 

Thanks for offering to teach me and set everything up. Currently i don't have that much time, because the exams start soon. I especially need way more practice in technical drawing gearboxes (which is of course not a skill relevant in the industry but we still have to learn it and they enjoy making it as hard as possible).

This weekend i wrote a small postprocessing script, which in combination with macros, which are automatically programmed by a python script, can set the printing speed for each feature while printing independently with M220 commands. It could also be used to set other parameters during printing this way.

Another small project was a program, which calculates the center of gravity of a gcode file, which ignores supports ,brim... and also can consider M221 commands. I made this so i could use it with unorthodox gcode modifications.

Have you seen the alpha release of prusa slicer, which now shows the actual printing speed with considering the acceleration. Hopefully this feature will be in orca slicer too.
